%YAML:1.0
---

width: 640
height: 480
num_classes: 3
ox_path: "../models/zc_nanox_rep_486_640_nopad.onnx"
eg_path: "../models/zc_nanox_rep_486_640_nopad.engine"
score_threshold: 0.5
nms_threshold: 0.25
ues_fp16: 1




rtsp_ip: "192.168.100.20"
rtsp_topic: "live"

max_q_size: 5
det_interval: 1
max_failed_size: 10
thread_wait_delay: 1
mode: 1
